#pragma once


enum HksError : __int32
{
	HKS_NO_ERROR = 0x0,
	LUA_ERRSYNTAX = -1,
	LUA_ERRFILE = -2,
	LUA_ERRRUN = -3,
	LUA_ERRMEM = -4,
	LUA_ERRERR = -5,
	HKS_THROWING_ERROR = -6,
	HKS_GC_YIELD = 0x1,
};

enum HksBytecodeEndianness : __int32
{
	HKS_BYTECODE_DEFAULT_ENDIAN = 0x0,
	HKS_BYTECODE_BIG_ENDIAN = 0x1,
	HKS_BYTECODE_LITTLE_ENDIAN = 0x2,
};

enum HksBytecodeSharingMode : __int64
{
	HKS_BYTECODE_SHARING_OFF = 0,
	HKS_BYTECODE_SHARING_ON = 1,
	HKS_BYTECODE_SHARING_SECURE = 2
};

enum HksObjectType : __int32
{
	TANY = -2,
	TNONE = -1,
	TNIL = 0x0,
	TBOOLEAN = 0x1,
	TLIGHTUSERDATA = 0x2,
	TNUMBER = 0x3,
	TSTRING = 0x4,
	TTABLE = 0x5,
	TFUNCTION = 0x6,
	TUSERDATA = 0x7,
	TTHREAD = 0x8,
	TIFUNCTION = 0x9,
	TCFUNCTION = 0xA,
	TUI64 = 0xB,
	TSTRUCT = 0xC,
	NUM_TYPE_OBJECTS = 0xE,
};

